---
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - ntpdate
    - zip
    - unzip
    - gcc
- name: install debian packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - shellcheck
    - libffi-dev
  when: ansible_os_family == "Debian"
- name: install rhel packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rpm-build 
    - rpm-devel 
    - rpmlint 
    - make
    - coreutils 
    - diffutils 
    - python-devel
    - patch 
    - rpmdevtools
    - openssl
    - openssl-devel
    - gcc-c++
  when: ansible_os_family == "RedHat"
- name: requests
  pip:
    name: requests
    version: 2.17.0
- name: pip install
  pip:
    name: ['awscli', 'pyhcl', 'docker', 'boto3', 'virtualenv']
- name: wonkyfix
  pip:
    name: 'requests'
    version: 2.20
- name: now install molecule
  pip:
    name: molecule
- name: optional docker install
  include: tasks/docker.yml
  when: options.docker
- name: default editor to vim
  shell: update-alternatives --set editor /usr/bin/vim.basic
  when: ansible_os_family == "debian"
- name: git-crypt for rhel
  include_tasks: rhel-git.yml
  when: ansible_os_family == "RedHat"