---
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - jq
    - ntpdate
    - pwgen
    - zip
    - unzip
    - gcc
- name: install debian packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - shellcheck
    - libffi-dev
  when: ansible_os_family == "Debian"
- name: install rhel packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rpm-build 
    - rpm-devel 
    - rpmlint 
    - make
    - coreutils 
    - diffutils 
    - patch 
    - rpmdevtools
    - openssl
    - openssl-devel
    - gcc-c++
  when: ansible_os_family == "RedHat"
- name: pip install
  pip:
    name: "{{ item }}"
  with_items:
    - awsebcli
    - awscli
    - pyhcl
    - ansible-lint
    - flake8
    - docker
    - boto3
    - virtualenv
- name: pip install versions
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - { name: setuptools, version: 36.3.0 }
    - { name: molecule, version: 1.25.0 }
- name: optional docker install
  include: tasks/docker.yml
  when: options.docker
- name: default editor to vim
  shell: update-alternatives --set editor /usr/bin/vim.basic
  when: ansible_os_family == "debian"
- name: git-crypt for rhel
  include_tasks: rhel-git.yml
  when: ansible_os_family == "RedHat"