---

- name: install docker prereqs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - software-properties-common
    - apt-transport-https
# - name: install docker GPG key
#   shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
- name: Add Docker Apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
# - name: install docker repo
#   shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
- name: Add Docker Repo
  apt_repository:
    repo:  "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
- name: apt update
  apt:
    update_cache: yes
