---

- name: install docker prereqs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: Add repository
  yum_repository:
    name: dockerCE
    description: Docker CE repo
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
- rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg
