---

- hosts: all
  connection: local
  become: true
  vars:
    - local_bin_dir: /usr/local/bin
    - packer_version: 1.2.5
    - terraform_version: 0.11.8
  vars_files:
    - ../secrets/vars.yml
  tasks:
    - name: hostname config
      replace:
        dest: "{{ item }}"
        regexp: '(\s+)ubuntu-xenial(\s+.*)?$'
        replace: '\1vagrant-tools\2'
      with_items:
        - /etc/hosts
        - /etc/hostname
    - name: hostnamectl
      shell: hostnamectl set-hostname vagrant-tools
    - name: install id_rsa ssh private key
      copy:
        src: /vagrant/secrets/id_rsa
        dest: /home/{{ vagrant_user }}/.ssh/id_rsa
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0600
    - name: ssh config
      template:
          src: templates/ssh_config.j2
          dest: /home/{{ vagrant_user }}/.ssh/config
          owner: "{{ vagrant_user }}"
          group: "{{ vagrant_user }}"
          mode: 0500
    - name: install extra packages
      apt:
        name: ['git-crypt', 'direnv', 'virtualenv']
        state: present
      when: ansible_os_family == "Debian"
    - name: Download ChefDK deb (moved early to prevent wifi issues)
      get_url:
          dest: /tmp/chef.deb
          url: https://packages.chef.io/files/stable/chefdk/3.1.0/ubuntu/18.04/chefdk_3.1.0-1_amd64.deb
          checksum: "sha256:ea5eaf7f729f217f5a33722d5b0a8b2aab6acd8f1f096a474eb44e5419bf3144"
      when: ansible_os_family == "Debian"
    - name: Download ChefDK rpm (moved early to prevent wifi issues)
      get_url:
          dest: /tmp/chef.rpm
          url: https://packages.chef.io/files/stable/chefdk/3.1.0/el/7/chefdk-3.1.0-1.el7.x86_64.rpm
          checksum: "sha256:3d96c2d9dd733602a055f8ca99789ed4857b02440037c69c954e4964d68f9a82"
      when: ansible_os_family == "RedHat"
    - name: tmux.conf
      copy:
        src: /vagrant/ansible/files/tmux.conf
        dest: /home/{{ vagrant_user }}/.tmux.conf
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0644
    - include: tasks/common.yml
    - name: install packer
      include: tasks/hashicorp_install.yml tool_name=packer tool_version={{packer_version}}
    - name: install terraform
      include: tasks/hashicorp_install.yml tool_name=terraform tool_version={{terraform_version}}
    - name: .bash_aliases
      copy:
        src: /vagrant/ansible/files/bash_aliases
        dest: /home/{{ vagrant_user }}/.bash_aliases
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0500
    - name: mkdir ~/.aws
      file:
        path: /home/{{ vagrant_user }}/.aws
        state: directory
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0755
    - name: add ~/.aws/config
      copy:
        src: /vagrant/secrets/aws_config
        dest: /home/{{ vagrant_user }}/.aws/config
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0500
      ignore_errors: true
    - name: add ~/.aws/credentials
      template:
        src: /vagrant/ansible/templates/aws_credentials.j2
        dest: /home/{{ vagrant_user }}/.aws/credentials
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0500
      ignore_errors: true
    - name: git config
      shell: "{{ item }}"
      with_items:
       - "su -c \"git config --global user.name '{{ user.full_name }}'\" - {{ vagrant_user }}"
       - "su -c \"git config --global user.email '{{ user.email }}'\" - {{ vagrant_user }}"
       - "su -c \"git config --global merge.ff yes\" - {{ vagrant_user }}"
       - "su -c \"git config --global color.ui auto\" - {{ vagrant_user }}"
    - name: mkdir ~/bin
      file:
        path: /home/{{ vagrant_user }}/bin
        state: directory
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: 0755
    - name: Install ChefDK deb
      apt:
        deb: /tmp/chef.deb
      when: ansible_os_family == "Debian"
    - name: Install ChefDK rpm
      yum:
        name: /tmp/chef.rpm
      when: ansible_os_family == "RedHat"
    - name: Install Kitchen-docker
      shell: "chef gem install kitchen-docker"